/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prova;

import Tela_principal.EscolhaPesonagem;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jamerson
 */
public class GabaritoExameDeSelecao extends javax.swing.JFrame {

    /**
     * Creates new form GabaritoExameDeSelecao
     */
    ButtonGroup g1 = new ButtonGroup();
    ButtonGroup g2 = new ButtonGroup();
    ButtonGroup g3 = new ButtonGroup();
    ButtonGroup g4 = new ButtonGroup();
    ButtonGroup g5 = new ButtonGroup();
    ButtonGroup g6 = new ButtonGroup();
    ButtonGroup g7 = new ButtonGroup();
    ButtonGroup g8 = new ButtonGroup();
    ButtonGroup g9 = new ButtonGroup();
    ButtonGroup g10 = new ButtonGroup();
    ButtonGroup g11 = new ButtonGroup();
    Prova p = new Prova();
    int lugar = 0;

    public GabaritoExameDeSelecao() {
        initComponents();
        p.setVisible(true);
        setIconImage(new ImageIcon("Res/logoBarra.png").getImage());
        jLabel13.setIcon(new ImageIcon("Res/imgexame.jpg"));
        setSize(360, 585);
        setLocation(630, 40);
        getContentPane().setBackground(Color.white);
        g1.add(jRadioButton1);
        g1.add(jRadioButton2);
        g1.add(jRadioButton3);
        g1.add(jRadioButton4);

        g2.add(jRadioButton5);
        g2.add(jRadioButton6);
        g2.add(jRadioButton7);
        g2.add(jRadioButton8);

        g3.add(jRadioButton9);
        g3.add(jRadioButton10);
        g3.add(jRadioButton11);
        g3.add(jRadioButton12);

        g4.add(jRadioButton17);
        g4.add(jRadioButton18);
        g4.add(jRadioButton19);
        g4.add(jRadioButton20);

        g5.add(jRadioButton21);
        g5.add(jRadioButton22);
        g5.add(jRadioButton23);
        g5.add(jRadioButton24);

        g6.add(jRadioButton13);
        g6.add(jRadioButton14);
        g6.add(jRadioButton15);
        g6.add(jRadioButton16);

        g7.add(jRadioButton25);
        g7.add(jRadioButton26);
        g7.add(jRadioButton27);
        g7.add(jRadioButton28);

        g8.add(jRadioButton29);
        g8.add(jRadioButton30);
        g8.add(jRadioButton31);
        g8.add(jRadioButton32);

        g9.add(jRadioButton33);
        g9.add(jRadioButton34);
        g9.add(jRadioButton35);
        g9.add(jRadioButton36);

        g10.add(jRadioButton37);
        g10.add(jRadioButton38);
        g10.add(jRadioButton39);
        g10.add(jRadioButton40);

        g11.add(jRadioButton41);
        g11.add(jRadioButton42);
        g11.add(jRadioButton43);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton43 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gabarito");
        setResizable(false);
        getContentPane().setLayout(null);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton1.setText("D");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 220, 40, 23);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton2.setText("A");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 100, 40, 23);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton3.setText("B");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(20, 140, 40, 23);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton4.setText("C");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 180, 40, 23);

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton5.setText("A");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(90, 100, 40, 23);

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton6.setText("B");
        jRadioButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(90, 140, 40, 23);

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton7.setText("C");
        jRadioButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(90, 180, 40, 23);

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton8.setText("D");
        jRadioButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(90, 220, 40, 23);

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton9.setText("A");
        jRadioButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(160, 100, 40, 23);

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton10.setText("B");
        jRadioButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(160, 140, 40, 23);

        jRadioButton11.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton11.setText("C");
        jRadioButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(160, 180, 40, 23);

        jRadioButton12.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton12.setText("D");
        jRadioButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(160, 220, 40, 23);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 70, 60, 180);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 70, 60, 180);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 180);

        jRadioButton13.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton13.setText("D");
        jRadioButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton13);
        jRadioButton13.setBounds(20, 410, 40, 23);

        jRadioButton14.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton14.setText("A");
        jRadioButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton14);
        jRadioButton14.setBounds(20, 290, 40, 23);

        jRadioButton15.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton15.setText("B");
        jRadioButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton15);
        jRadioButton15.setBounds(20, 330, 40, 23);

        jRadioButton16.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton16.setText("C");
        jRadioButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton16);
        jRadioButton16.setBounds(20, 370, 40, 23);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "6", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 60, 180);

        jButton1.setBackground(new java.awt.Color(217, 39, 27));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Entregar Gabarito e Finalizar a Prova");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 530, 340, 23);

        jPanel1.setBackground(new java.awt.Color(105, 184, 44));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setText("Gabarito de : Exame Da Silva");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 20, 330, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 70);

        jRadioButton41.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton41.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton41.setText("Informática");
        jRadioButton41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton41);
        jRadioButton41.setBounds(10, 470, 160, 20);

        jRadioButton42.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton42.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton42.setText("Meio Ambiente");
        jRadioButton42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton42);
        jRadioButton42.setBounds(180, 470, 139, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jRadioButton20.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton20.setText("D");
        jRadioButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton20);
        jRadioButton20.setBounds(250, 220, 40, 23);

        jRadioButton19.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton19.setText("C");
        jRadioButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton19);
        jRadioButton19.setBounds(250, 180, 40, 30);

        jRadioButton18.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton18.setText("B");
        jRadioButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton18);
        jRadioButton18.setBounds(250, 140, 40, 23);

        jRadioButton17.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton17.setText("A");
        jRadioButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton17);
        jRadioButton17.setBounds(250, 100, 40, 23);

        jRadioButton22.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton22.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton22.setText("B");
        jRadioButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton22);
        jRadioButton22.setBounds(320, 140, 40, 23);

        jRadioButton21.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton21.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton21.setText("A");
        jRadioButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton21);
        jRadioButton21.setBounds(320, 100, 40, 23);

        jRadioButton23.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton23.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton23.setText("C");
        jRadioButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton23);
        jRadioButton23.setBounds(320, 180, 40, 23);

        jRadioButton24.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton24.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton24.setText("D");
        jRadioButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton24);
        jRadioButton24.setBounds(320, 220, 40, 23);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(380, 80, 120, 140);

        jRadioButton25.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton25.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton25.setText("D");
        jRadioButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton25);
        jRadioButton25.setBounds(110, 410, 40, 23);

        jRadioButton26.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton26.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton26.setText("A");
        jRadioButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton26);
        jRadioButton26.setBounds(110, 290, 40, 23);

        jRadioButton27.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton27.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton27.setText("B");
        jRadioButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton27);
        jRadioButton27.setBounds(110, 330, 40, 23);

        jRadioButton28.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton28.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton28.setText("C");
        jRadioButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton28);
        jRadioButton28.setBounds(110, 370, 40, 23);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(100, 260, 60, 180);

        jRadioButton29.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton29.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton29.setText("D");
        jRadioButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton29);
        jRadioButton29.setBounds(180, 410, 40, 23);

        jRadioButton30.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton30.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton30.setText("A");
        jRadioButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton30);
        jRadioButton30.setBounds(180, 290, 40, 23);

        jRadioButton31.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton31.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton31.setText("B");
        jRadioButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton31);
        jRadioButton31.setBounds(180, 330, 40, 23);

        jRadioButton32.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton32.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton32.setText("C");
        jRadioButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton32);
        jRadioButton32.setBounds(180, 370, 40, 23);

        jRadioButton33.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton33.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton33.setText("D");
        jRadioButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton33);
        jRadioButton33.setBounds(250, 410, 40, 23);

        jRadioButton34.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton34.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton34.setText("A");
        jRadioButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton34);
        jRadioButton34.setBounds(250, 290, 40, 23);

        jRadioButton35.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton35.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton35.setText("B");
        jRadioButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton35);
        jRadioButton35.setBounds(250, 330, 40, 23);

        jRadioButton36.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton36.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton36.setText("C");
        jRadioButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton36);
        jRadioButton36.setBounds(250, 370, 40, 23);

        jRadioButton37.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton37.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton37.setText("D");
        jRadioButton37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton37);
        jRadioButton37.setBounds(320, 410, 40, 23);

        jRadioButton38.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton38.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton38.setText("A");
        jRadioButton38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton38);
        jRadioButton38.setBounds(320, 290, 40, 23);

        jRadioButton39.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton39.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton39.setText("B");
        jRadioButton39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton39);
        jRadioButton39.setBounds(320, 330, 40, 23);

        jRadioButton40.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton40.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jRadioButton40.setText("C");
        jRadioButton40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jRadioButton40);
        jRadioButton40.setBounds(320, 370, 40, 23);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(310, 263, 60, 178);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Selecione Seu Curso:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 440, 170, 30);

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "8", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 260, 60, 180);

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "9", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(240, 260, 60, 180);

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(240, 70, 60, 180);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 10)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 70, 60, 180);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-20, 0, 380, 470);

        jRadioButton43.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton43.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jRadioButton43.setText("Agroecologia");
        jRadioButton43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jRadioButton43);
        jRadioButton43.setBounds(10, 500, 127, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton41.isSelected() || jRadioButton42.isSelected() || jRadioButton43.isSelected()) {
            if (SeSelecionouRadioPanel1() && SeSelecionouRadioPanel2() && SeSelecionouRadioPanel3() && SeSelecionouRadioPanel4() && SeSelecionouRadioPanel5() && SeSelecionouRadioPanel6() && SeSelecionouRadioPanel7() && SeSelecionouRadioPanel8() && SeSelecionouRadioPanel9() && SeSelecionouRadioPanel10()) {
                if (testePassou1()) {
                    if (!p.getNome().equals("")) {

                        String nome = p.getNome();
                        String arquivo1 = "Res/Dados.txt";
                        FileWriter fw1;
                        try {
                            fw1 = new FileWriter(arquivo1);
                            BufferedWriter bw1 = new BufferedWriter(fw1);
                            bw1.write(nome);
                            bw1.newLine();
                            bw1.write("1234");
                            bw1.newLine();
                            bw1.close();
                            fw1.close();
                        } catch (IOException ex) {
                            Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        if (jRadioButton41.isSelected()) {
                            String arquivo = "Res/Dados.txt";
                            FileWriter fw;
                            try {
                                fw = new FileWriter(arquivo, true);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write("informatica");
                                bw.newLine();
                                bw.close();
                                fw.close();
                            } catch (IOException ex) {
                                Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        if (jRadioButton42.isSelected()) {
                            String arquivo = "Res/Dados.txt";
                            FileWriter fw;
                            try {
                                fw = new FileWriter(arquivo, true);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write("meio ambiente");
                                bw.newLine();
                                bw.close();
                                fw.close();
                            } catch (IOException ex) {
                                Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        if (jRadioButton43.isSelected()) {
                            String arquivo = "Res/Dados.txt";
                            FileWriter fw;
                            try {
                                fw = new FileWriter(arquivo, true);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write("agroecologia");
                                bw.newLine();
                                bw.close();
                                fw.close();
                            } catch (IOException ex) {
                                Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        JOptionPane.showMessageDialog(null, "Você passou em " + lugar + "º lugar.\nParabens!\nOBS: A questão 4 foi anulada", "Parabens", JOptionPane.INFORMATION_MESSAGE);
                        EscolhaPesonagem e = new EscolhaPesonagem();
                        e.setVisible(true);

                        p.dispose();
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Coloque seu nome na prova", "Coloque seu nome", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    Naopassou np = new Naopassou();
                    np.setVisible(true);
                    p.dispose();
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Responda todas as questoes.", "Responda as questoes", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um curso.", "Selecionar curso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean testePassou1() {
        int cont = 0;
        if (jRadioButton3.isSelected()) {
            cont++;
        }
        if (jRadioButton6.isSelected()) {
            cont++;
        }
        if (jRadioButton10.isSelected()) {
            cont++;
        }
        if (jRadioButton17.isSelected() || jRadioButton18.isSelected() || jRadioButton19.isSelected() || jRadioButton20.isSelected()) {
            cont++;
        }
        if (jRadioButton21.isSelected()) {
            cont++;
        }
        if (jRadioButton16.isSelected()) {
            cont++;
        }
        if (jRadioButton28.isSelected()) {
            cont++;
        }
        if (jRadioButton31.isSelected()) {
            cont++;
        }
        if (jRadioButton34.isSelected()) {
            cont++;
        }
        if (jRadioButton39.isSelected()) {
            cont++;
        }
        if (cont >= 3) {
            if (cont == 3) {
                lugar = 8;
            }
            if (cont == 4) {
                lugar = 7;
            }
            if (cont == 5) {
                lugar = 6;
            }
            if (cont == 6) {
                lugar = 5;
            }
            if (cont == 7) {
                lugar = 4;
            }
            if (cont == 8) {
                lugar = 3;
            }
            if (cont == 9) {
                lugar = 2;
            }
            if (cont == 10) {
                lugar = 1;
            }
        } else {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel1() {
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected() && !jRadioButton3.isSelected() && !jRadioButton4.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel2() {
        if (!jRadioButton5.isSelected() && !jRadioButton6.isSelected() && !jRadioButton7.isSelected() && !jRadioButton8.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel3() {
        if (!jRadioButton9.isSelected() && !jRadioButton10.isSelected() && !jRadioButton11.isSelected() && !jRadioButton12.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel4() {
        if (!jRadioButton17.isSelected() && !jRadioButton18.isSelected() && !jRadioButton19.isSelected() && !jRadioButton20.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel5() {
        if (!jRadioButton21.isSelected() && !jRadioButton22.isSelected() && !jRadioButton23.isSelected() && !jRadioButton24.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel6() {
        if (!jRadioButton13.isSelected() && !jRadioButton14.isSelected() && !jRadioButton15.isSelected() && !jRadioButton16.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel7() {
        if (!jRadioButton25.isSelected() && !jRadioButton26.isSelected() && !jRadioButton27.isSelected() && !jRadioButton28.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel8() {
        if (!jRadioButton29.isSelected() && !jRadioButton30.isSelected() && !jRadioButton31.isSelected() && !jRadioButton32.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel9() {
        if (!jRadioButton33.isSelected() && !jRadioButton34.isSelected() && !jRadioButton35.isSelected() && !jRadioButton36.isSelected()) {
            return false;
        }
        return true;
    }

    private boolean SeSelecionouRadioPanel10() {
        if (!jRadioButton37.isSelected() && !jRadioButton38.isSelected() && !jRadioButton39.isSelected() && !jRadioButton40.isSelected()) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GabaritoExameDeSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GabaritoExameDeSelecao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
