package TFasePrincipal;

import JogoMemoria.Memoria;
import Prova.Prova;
import com.sun.awt.AWTUtilities;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jamerson
 */
public class TelaDePergunta11 extends javax.swing.JFrame {

    /**
     * Creates new form TelaDePergunta1
     */
    String trocarJogo = "";
    boolean cont = false;
    boolean passou = false;
    int numbonus, numbonus2;
    Timer t, fimbonus;
    int resposta = 0;

    public TelaDePergunta11() {
        initComponents();
        setIconImage(new ImageIcon("Res/logoBarra.png").getImage());
        jLabel6.setIcon(new ImageIcon("Res/ICONETROCA.png"));
        jLabel3.setIcon(new ImageIcon("Res/icone tirar.png"));
        setSize(0, 0);
        jButton2.setFocusable(false);
        jButton6.setFocusable(false);
        jButton7.setFocusable(false);
        jButton8.setFocusable(false);
        jButton9.setFocusable(false);
        AWTUtilities.setWindowOpacity(this, ((float) 0.93));
        String caminhoarquivo = "Res/Dados/NumeroBonus.txt";
        String linha = "", textotxt = "";
        FileReader fr;
        try {
            fr = new FileReader(caminhoarquivo);
            BufferedReader br = new BufferedReader(fr);
            try {
                while (br.ready()) {
                    linha = "";
                    linha += br.readLine();
                    if (!linha.equals("")) {
                        textotxt += linha + "\n";
                    }
                }
                textotxt = textotxt.substring(0, textotxt.length() - 1);
                br.close();
                fr.close();
            } catch (IOException ex) {
                Logger.getLogger(Prova.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Prova.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] bonus = textotxt.split("@");
        numbonus = Integer.parseInt(bonus[0]);
        numbonus2 = Integer.parseInt(bonus[1]);
        jLabel6.setText("" + numbonus);
        jLabel3.setText("" + numbonus2);
    }

    public void setAlternativas(String alternativastxt) {
        String alternativas[] = alternativastxt.split("-");
        jButton2.setText(alternativas[0]);
        jButton6.setText(alternativas[1]);
        jButton7.setText(alternativas[2]);
        jButton9.setText(alternativas[3]);
        jButton8.setText(alternativas[4]);
    }

    public void setMateria(String materia) {
        jLabel2.setText(materia);
    }

    public void setPergunta(String pergunta) {
        jLabel5.setText(pergunta);
    }

    public void setResposta(int resposta) {
        this.resposta = resposta;
    }

    public boolean isCont() {
        return cont;
    }

    public boolean isPassou() {
        return passou;
    }

    public void Inicio() {
        resposta = 0;
        passou = false;
        trocarJogo = "";
        jButton2.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton9.setVisible(true);
        jButton8.setVisible(true);
        jLabel3.setEnabled(true);
        jLabel6.setEnabled(true);
    }

    public void setCont(boolean cont) {
        this.cont = cont;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("8 Planetas");
        jButton2.setDoubleBuffered(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 170, 540, 50);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Responda corretamente:");
        jLabel2.setDoubleBuffered(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 810, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(null);
        jLabel3.setToolTipText("Eliminar alternativas");
        jLabel3.setDoubleBuffered(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(670, 270, 170, 70);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton6.setText("10 Planetas");
        jButton6.setDoubleBuffered(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(60, 230, 540, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton7.setText("11 Planetas");
        jButton7.setDoubleBuffered(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(60, 290, 540, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8.setText("7 Planetas");
        jButton8.setDoubleBuffered(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(60, 410, 540, 50);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton9.setText("12 Planetas");
        jButton9.setDoubleBuffered(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(60, 350, 540, 50);

        jLabel4.setText("jLabel4");
        jLabel4.setDoubleBuffered(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 180, 34, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantos planetas tem no sistema solar ?");
        jLabel5.setDoubleBuffered(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 90, 790, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(null);
        jLabel6.setToolTipText("Trocar a pergunta por jogo");
        jLabel6.setDoubleBuffered(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 180, 230, 60);

        jLabel1.setDoubleBuffered(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel7.setDoubleBuffered(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 0, 0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TFasePrincipal/quadro2.png"))); // NOI18N
        jLabel8.setDoubleBuffered(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 880, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Acertou() {
        JOptionPane.showMessageDialog(null, "Parabéns, você acertou a pergunta", "Parabéns!", JOptionPane.PLAIN_MESSAGE, new ImageIcon("Res/LIKE.png"));
    }

    private void Errou() {
        String respostacerta = "";
        if (resposta == 1) {
            respostacerta = jButton2.getText();
        }
        if (resposta == 2) {
            respostacerta = jButton6.getText();
        }
        if (resposta == 3) {
            respostacerta = jButton7.getText();
        }
        if (resposta == 4) {
            respostacerta = jButton9.getText();
        }
        if (resposta == 5) {
            respostacerta = jButton8.getText();
        }
        JOptionPane.showMessageDialog(null, "Infelizmente você errou\n A resposta certa era: " + respostacerta, "Errou!", JOptionPane.PLAIN_MESSAGE, new ImageIcon("Res/deslike.png"));

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (resposta == 1) {
            Acertou();
            passou = true;
            cont = true;
            Sair();
        } else {
            Errou();
            cont = true;
            Sair();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (resposta == 2) {
            Acertou();
            passou = true;
            cont = true;
            Sair();
        } else {
            Errou();
            cont = true;
            Sair();
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (resposta == 3) {
            Acertou();
            passou = true;
            cont = true;
            Sair();
        } else {
            Errou();
            cont = true;
            Sair();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (resposta == 5) {
            Acertou();
            passou = true;
            cont = true;
            Sair();
        } else {
            cont = true;
            Errou();
            Sair();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (resposta == 4) {
            Acertou();
            passou = true;
            cont = true;
            Sair();
        } else {
            Errou();
            cont = true;
            Sair();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (numbonus2 > 0) {
            jLabel3.setEnabled(false);
            jLabel6.setEnabled(false);
            int contador = 0;
            String saiu = "" + resposta;
            while (contador <= 2) {
                Random random = new Random();
                int z = -1;
                boolean jasaiu = true;
                while (jasaiu) {
                    jasaiu = true;
                    z = random.nextInt(5) + 1;
                    String numssaiu[] = saiu.split("-");
                    int j = 0;
                    for (int i = 0; i < numssaiu.length; i++) {
                        if (numssaiu[i].equals("" + z)) {
                            j++;
                        }
                    }
                    if (j == 0) {
                        jasaiu = false;
                    }
                    if (!jasaiu) {
                        if (z == 1) {
                            jButton2.setVisible(false);
                            if (saiu.equals("")) {
                                saiu += "" + z;
                            } else {
                                saiu += "-" + z;
                            }
                        }
                        if (z == 2) {
                            jButton6.setVisible(false);
                            if (saiu.equals("")) {
                                saiu += "" + z;
                            } else {
                                saiu += "-" + z;
                            }
                        }
                        if (z == 3) {
                            jButton7.setVisible(false);
                            if (saiu.equals("")) {
                                saiu += "" + z;
                            } else {
                                saiu += "-" + z;
                            }
                        }
                        if (z == 4) {
                            jButton9.setVisible(false);
                            if (saiu.equals("")) {
                                saiu += "" + z;
                            } else {
                                saiu += "-" + z;
                            }
                        }
                        if (z == 5) {
                            jButton8.setVisible(false);
                            if (saiu.equals("")) {
                                saiu += "" + z;
                            } else {
                                saiu += "-" + z;
                            }
                        }
                    }
                }
                contador++;
            }
            String arquivo = "Res/Dados/NumeroBonus.txt";
            FileWriter fw1;
            try {
                fw1 = new FileWriter(arquivo);
                BufferedWriter bw1 = new BufferedWriter(fw1);
                if (numbonus2 > 0) {
                    bw1.write(numbonus + "@" + (numbonus2 - 1));
                } else {
                    bw1.write(0 + "@" + 0);
                }
                numbonus2 = numbonus2 - 1;
                bw1.close();
                fw1.close();
            } catch (IOException ex) {
                Logger.getLogger(SePassou.class.getName()).log(Level.SEVERE, null, ex);
            }
            jLabel3.setText("" + numbonus2);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        if (numbonus > 0) {
            setVisible(false);
            jLabel3.setEnabled(false);
            jLabel6.setEnabled(false);
            String caminhoarquivo = "Res/Dados/ProximoBonus.txt", arquivo = "Res/Dados/NumeroBonus.txt";
            String linha = "", textotxt = "";
            FileReader fr;
            try {
                fr = new FileReader(caminhoarquivo);
                BufferedReader br = new BufferedReader(fr);
                try {
                    while (br.ready()) {
                        linha = "";
                        linha += br.readLine();
                        if (!linha.equals("")) {
                            textotxt += linha + "\n";
                        }
                    }
                    textotxt = textotxt.substring(0, textotxt.length() - 1);
                    br.close();
                    fr.close();
                } catch (IOException ex) {
                    Logger.getLogger(Prova.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (textotxt.equals("memoria1")) {
                FileWriter fw;
                try {
                    fw = new FileWriter(caminhoarquivo);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write("memoria2");
                    bw.close();
                    fw.close();
                    final Memoria m = new Memoria("Res/JogosExtras/Memoria/1.png", "Res/JogosExtras/Memoria/2.png", "Res/JogosExtras/Memoria/3.png", "Res/JogosExtras/Memoria/4.png", "Res/JogosExtras/Memoria/5.png", "Res/JogosExtras/Memoria/6.png", "Res/JogosExtras/Memoria/7.png", "Res/JogosExtras/Memoria/8.png");
                    m.setVisible(true);
                    ActionListener action;
                    action = new ActionListener() {
                        public void actionPerformed(@SuppressWarnings("unused") java.awt.event.ActionEvent e) {
                            if (m.getTerminou()) {
                                fimbonus.stop();
                                cont = true;
                                passou = m.getAcertou();
                                m.dispose();
                            }
                        }
                    };
                    fimbonus = new Timer(50, action);
                    fimbonus.start();

                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
                FileWriter fw1;
                try {
                    fw1 = new FileWriter(arquivo);
                    BufferedWriter bw1 = new BufferedWriter(fw1);
                    if (numbonus > 0) {
                        bw1.write((numbonus - 1) + "@" + numbonus2);
                    } else {
                        bw1.write(0 + "@" + 0);
                    }
                    numbonus = numbonus - 1;
                    bw1.close();
                    fw1.close();
                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (textotxt.equals("memoria2")) {
                FileWriter fw;
                try {
                    fw = new FileWriter(caminhoarquivo);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write("memoria3");
                    bw.close();
                    fw.close();
                    final Memoria m = new Memoria("Res/JogosExtras/Memoria/1.png", "Res/JogosExtras/Memoria/2.png", "Res/JogosExtras/Memoria/3.png", "Res/JogosExtras/Memoria/4.png", "Res/JogosExtras/Memoria/5.png", "Res/JogosExtras/Memoria/6.png", "Res/JogosExtras/Memoria/7.png", "Res/JogosExtras/Memoria/8.png");
                    m.setVisible(true);
                    ActionListener action;
                    action = new ActionListener() {
                        public void actionPerformed(@SuppressWarnings("unused") java.awt.event.ActionEvent e) {
                            if (m.getTerminou()) {
                                fimbonus.stop();
                                cont = true;
                                passou = m.getAcertou();
                                m.dispose();
                            }
                        }
                    };
                    fimbonus = new Timer(50, action);
                    fimbonus.start();

                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
                FileWriter fw1;
                try {
                    fw1 = new FileWriter(arquivo);
                    BufferedWriter bw1 = new BufferedWriter(fw1);
                    if (numbonus > 0) {
                        bw1.write((numbonus - 1) + "@" + numbonus2);
                    } else {
                        bw1.write(0 + "@" + 0);
                    }
                    numbonus = numbonus - 1;
                    bw1.close();
                    fw1.close();
                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (textotxt.equals("memoria3")) {
                FileWriter fw;
                try {
                    fw = new FileWriter(caminhoarquivo);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write("memoria1");
                    bw.close();
                    fw.close();
                    final Memoria m = new Memoria("Res/JogosExtras/Memoria/1.png", "Res/JogosExtras/Memoria/2.png", "Res/JogosExtras/Memoria/3.png", "Res/JogosExtras/Memoria/4.png", "Res/JogosExtras/Memoria/5.png", "Res/JogosExtras/Memoria/6.png", "Res/JogosExtras/Memoria/7.png", "Res/JogosExtras/Memoria/8.png");
                    m.setVisible(true);
                    ActionListener action;
                    action = new ActionListener() {
                        public void actionPerformed(@SuppressWarnings("unused") java.awt.event.ActionEvent e) {
                            if (m.getTerminou()) {
                                fimbonus.stop();
                                cont = true;
                                passou = m.getAcertou();
                                m.dispose();
                            }
                        }
                    };
                    fimbonus = new Timer(50, action);
                    fimbonus.start();

                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
                FileWriter fw1;
                try {
                    fw1 = new FileWriter(arquivo);
                    BufferedWriter bw1 = new BufferedWriter(fw1);
                    if (numbonus > 0) {
                        bw1.write((numbonus - 1) + "@" + numbonus2);
                    } else {
                        bw1.write(0 + "@" + 0);
                    }
                    numbonus = numbonus - 1;
                    bw1.close();
                    fw1.close();
                } catch (IOException ex) {
                    Logger.getLogger(TelaDePergunta11.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            jLabel6.setText("" + numbonus);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public void setvisevel(boolean x) {
        if (x) {

            efeito();
        }
    }

    private void efeito() {

        new Thread() {
            public void run() {
                for (int i = 1; i < 600; i += 10) {
                    try {
                        sleep(3);


                    } catch (InterruptedException ex) {
                        Logger.getLogger(TelaDePergunta11.class
                                .getName()).log(Level.SEVERE, null, ex);
                    }


                    setSize(i + 290, i);
                    setVisible(true);
                    setLocationRelativeTo(null);
                }
                stop();
            }
        }.start();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta11.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta11.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta11.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta11.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDePergunta11().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void Sair() {
        for (int i = 600; i > 0; i -= 10) {
            try {
                sleep(5);


            } catch (InterruptedException ex) {
                Logger.getLogger(TelaDePergunta11.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            setSize(i + 290, i);
        }
        setSize(0, 0);
        // setVisible(false);
        //dispose();
    }
}
