/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Tutoria;

import TFasePrincipal.Fase;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DANIEL
 */
public class TelaDePergunta extends javax.swing.JFrame {

    boolean cont = false;
    String materia, ano;
    String resposta = "", respostacerta;

    /**
     * Creates new form TelaDePergunta
     */
    public TelaDePergunta() {
        initComponents();
        setIconImage(new ImageIcon("Res/logoBarra.png").getImage());
        setSize(890, 600);
        jButton2.setFocusable(false);
        jButton6.setFocusable(false);
        jButton7.setFocusable(false);
        jButton9.setFocusable(false);
        setarPergunta("fisica", "4");
    }

    public void setAno(String materia, String ano) {
        this.ano = ano;
        this.materia = materia;
        setarPergunta(materia, ano);

    }

    public boolean isCont() {
        return cont;
    }

    public void setvisevel(boolean x) {
        if (x) {
            efeito();
        }
    }

    private void efeito() {
        setLocationRelativeTo(null);
        setBackground(new Color(0f, 0f, 0f, 0f));
        AWTUtilities.setWindowOpacity(this, (0.0f));
        setVisible(true);
        float f = 0.0f;
        for (int i = 0; i <= 31; i++) {
            AWTUtilities.setWindowOpacity(this, (f));
            f += 0.03;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Responda corretamente:");
        jLabel2.setDoubleBuffered(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(109, 47, 498, 45);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantos planetas tem no sistema solar ?");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setDoubleBuffered(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 110, 724, 100);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("8 Planetas");
        jButton2.setDoubleBuffered(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(109, 230, 710, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton6.setText("B)\tPalavras com acento na última silaba");
        jButton6.setDoubleBuffered(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(109, 286, 710, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton7.setText("11 Planetas");
        jButton7.setDoubleBuffered(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(109, 342, 710, 50);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton9.setText("12 Planetas");
        jButton9.setDoubleBuffered(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(109, 398, 710, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TFasePrincipal/quadro2.png"))); // NOI18N
        jLabel1.setDoubleBuffered(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean verSeJaLiberou(String jogo) {
        String arquivo = "Res/Dados//JogosDesbloqueados.txt", lin, f = "";
        try {
            FileReader fr = new FileReader(arquivo);
            BufferedReader br = new BufferedReader(fr);
            try {
                while (br.ready()) {
                    lin = "";
                    lin += br.readLine();
                    if (!lin.equals("")) {
                        f += lin + "\n";
                    }
                }
                if (!f.equals("")) {
                    f = f.substring(0, f.length() - 1);
                }
            } catch (IOException ex) {
                Logger.getLogger(TelaDePergunta.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaDePergunta.class.getName()).log(Level.SEVERE, null, ex);
        }
        String jogos[] = f.split("-");
        int j = 0;
        for (int i = 0; i < jogos.length; i++) {
            if (jogos[i].equals(jogo)) {
                j++;
            }
        }
        if (j == 0) {
            return true;
        }
        return false;
    }

    public void acertou() {
        JOptionPane.showMessageDialog(null, "Parabéns, acertou a pergunta.\nLiberou um novo jogo");
        String arquivo = "Res/Dados/JogosDesbloqueados.txt";
        String jogo = "";
        switch (ano) {
            case "2":
                if (verSeJaLiberou("caca")) {
                    jogo = "-caca";
                }
                break;
            case "3":
                if (verSeJaLiberou("velha")) {
                    jogo = "-velha";
                }
                break;
            case "4":
                if (verSeJaLiberou("cruzadas")) {
                    jogo = "-cruzadas";
                }
                break;
        }
        FileWriter fw;
        try {
            fw = new FileWriter(arquivo, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(jogo);
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(TelaDePergunta.class.getName()).log(Level.SEVERE, null, ex);
        }
        cont = true;
    }

    public void errou() {
        JOptionPane.showMessageDialog(null, "Errou a pergunta!\nA Resposta certa era: " + respostacerta);
        cont = true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (resposta.equals("1")) {
            acertou();
        } else {
            errou();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (resposta.equals("2")) {
            acertou();
        } else {
            errou();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (resposta.equals("3")) {
            acertou();
        } else {
            errou();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (resposta.equals("4")) {
            acertou();
        } else {
            errou();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDePergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDePergunta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void setarPergunta(String materia, String ano) {
        String arquivo = "Res/Tutoria/" + materia + "/" + ano + "/perguntas.txt", linha = "", f = "";
        try {
            FileReader fr = new FileReader(arquivo);
            BufferedReader br = new BufferedReader(fr);
            try {
                while (br.ready()) {
                    linha = "";
                    linha += br.readLine();
                    if (!linha.equals("")) {
                        f += linha + "\n";
                    }
                }
                f = f.substring(0, f.length() - 1);
            } catch (IOException ex) {
                Logger.getLogger(Fase.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fase.class.getName()).log(Level.SEVERE, null, ex);
        }
        String perguntas[] = f.split("\n");
        Random r = new Random();
        int numerodapergunta = r.nextInt(perguntas.length);
        String perguntasAlternativasEResposta[] = perguntas[numerodapergunta].split("@");
        String texto[] = perguntasAlternativasEResposta[0].split("&");
        jLabel3.setText("<html>");
        for (int i = 0; i < texto.length; i++) {
            if (i != texto.length - 1) {
                jLabel3.setText(jLabel3.getText() + "<br><p>" + texto[i] + "</p>");
            } else {
                jLabel3.setText(jLabel3.getText() + "<br><p>" + texto[i] + "</p></html>");
            }
        }
        String alternativas[] = perguntasAlternativasEResposta[1].split("-");
        jButton2.setText(alternativas[0]);
        jButton6.setText(alternativas[1]);
        jButton7.setText(alternativas[2]);
        jButton9.setText(alternativas[3]);
        resposta = perguntasAlternativasEResposta[2];
        respostacerta = alternativas[Integer.parseInt(resposta) - 1];
    }
}
